CREATE TABLE tarea (
    id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo      VARCHAR2(200) NOT NULL,
    completada  NUMBER(1) DEFAULT 0 NOT NULL,
    creada_en   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
